//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeGrpWorkout
    {
        public int Start_Age { get; set; }
        public int End_Age { get; set; }
        public string Workout_Plan { get; set; }
        public string Calories { get; set; }
    }
}
