//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSymptom
    {
        public string EmailAddress { get; set; }
        public string Symptoms { get; set; }
        public int UserId { get; set; }
    
        public virtual SymptomsOrDisease SymptomsOrDisease { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
