//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHealthInfo
    {
        public string EmailId { get; set; }
        public Nullable<int> Calories_Day_1 { get; set; }
        public Nullable<int> Calories_Day_2 { get; set; }
        public Nullable<int> Calories_Day_3 { get; set; }
        public Nullable<int> Calories_Day_4 { get; set; }
        public Nullable<int> Calories_Day_5 { get; set; }
        public Nullable<int> Calories_Day_6 { get; set; }
        public Nullable<int> Calories_Day_7 { get; set; }
        public Nullable<int> CurrentCalories { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<System.DateTime> FertilityDate { get; set; }
        public string Medication1 { get; set; }
        public Nullable<System.DateTime> StartDateM1 { get; set; }
        public Nullable<int> DurationM1 { get; set; }
        public string Medication2 { get; set; }
        public Nullable<System.DateTime> StartDateM2 { get; set; }
        public Nullable<int> DurationM2 { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
